import { useEffect, useMemo, useRef, useState } from 'react'
import { SunnahPage } from './Sunnah'
import './App.css'

const STORAGE = { route: 'tilawat:last-route', theme: 'tilawat:theme', sheikh: 'tilawat:selected-sheikh', audio: 'tilawat:audio-position' }
const routeLabels = { '/': 'الرئيسية', '/recitations': 'التلاوات', '/quran': 'القرآن الكريم', '/hadith': 'الأحاديث النبوية ﷺ', '/prophets': 'قصص الأنبياء عليهم السلام', '/adhkar': 'الأذكار والأدعية', '/seerah': 'السيرة النبوية', '/search': 'البحث الشامل', '/sources': 'المصادر والتخريج', '/sunnah': 'سنن النبي ﷺ' }
const sheikhsData = [
  { name: 'الشيخ ياسر الدوسري', title: 'صلاة المغرب — 18 محرم 1448 هـ', surah: 'سورة الكهف 107 - 110، سورة مريم 96 - 98', location: 'المسجد الحرام', audioSrc: 'https://files.manuscdn.com/user_upload_by_module/session_file/310519663960426511/NYHfkEdjTzaUAdcT.mp3' },
  { name: 'الشيخ فيصل غزاوي', title: 'صلاة المغرب — 2 ربيع الآخر 1448 هـ', surah: 'سورتي الكوثر والنصر', location: 'المسجد الحرام', audioSrc: 'https://files.manuscdn.com/user_upload_by_module/session_file/310519663960426511/WuXffcYMfFZTTDoW.mp3' },
  { name: 'الشيخ الوليد الشمسان', title: 'صلاة الفجر — 1 شعبان 1447 هـ', surah: 'سورة القصص، من الآية 76 إلى 88', location: 'المسجد الحرام', audioSrc: 'https://files.manuscdn.com/user_upload_by_module/session_file/310519663960426511/bWIptAoginZcHYqQ.mp3' },
]
function getStored(key, fallback = '') { try { return localStorage.getItem(key) || fallback } catch { return fallback } }
function readRoute() { const path = window.location.pathname; return routeLabels[path] ? path : getStored(STORAGE.route, '/') }
function navigate(path) { window.history.pushState({}, '', path); window.dispatchEvent(new PopStateEvent('popstate')) }

export default function App() {
  const [route, setRoute] = useState(readRoute)
  const [theme, setTheme] = useState(() => getStored(STORAGE.theme, 'dark'))
  const [isDropdownOpen, setIsDropdownOpen] = useState(false)
  const [selectedSheikh, setSelectedSheikh] = useState(() => getStored(STORAGE.sheikh, sheikhsData[0].name))
  const [audioPosition, setAudioPosition] = useState(() => Number(getStored(STORAGE.audio, '0')) || 0)
  const audioRef = useRef(null)
  const currentRecitation = useMemo(() => sheikhsData.find((s) => s.name === selectedSheikh) || sheikhsData[0], [selectedSheikh])

  useEffect(() => { const onPop = () => setRoute(readRoute()); window.addEventListener('popstate', onPop); return () => window.removeEventListener('popstate', onPop) }, [])
  useEffect(() => { localStorage.setItem(STORAGE.route, route); localStorage.setItem(STORAGE.theme, theme); document.documentElement.dataset.theme = theme }, [route, theme])
  useEffect(() => { localStorage.setItem(STORAGE.sheikh, selectedSheikh) }, [selectedSheikh])
  useEffect(() => { const audio = audioRef.current; if (!audio) return; const restore = () => { if (audioPosition > 0 && audioPosition < audio.duration) audio.currentTime = audioPosition }; audio.addEventListener('loadedmetadata', restore); return () => audio.removeEventListener('loadedmetadata', restore) }, [currentRecitation.audioSrc, audioPosition])
  const go = (path) => { setIsDropdownOpen(false); navigate(path) }
  const toggleTheme = () => setTheme((value) => value === 'dark' ? 'light' : 'dark')
  const saveAudio = () => { const position = audioRef.current?.currentTime || 0; setAudioPosition(position); localStorage.setItem(STORAGE.audio, String(position)) }

  return <div dir="rtl" className="site-shell">
    <header className="topbar"><div className="topbar-inner"><button className="brand" onClick={() => go('/')} aria-label="العودة إلى الرئيسية"><span className="brand-mark">🕌</span><span><strong>منصة تلاوات الحرمين</strong><small>صحبة قرآنية هادئة</small></span></button><div className="header-actions"><button className="theme-toggle" onClick={toggleTheme} aria-label={`تفعيل الوضع ${theme === 'dark' ? 'الفاتح' : 'الداكن'}`} title="تبديل المظهر">{theme === 'dark' ? '☀️ الوضع الفاتح' : '🌙 الوضع الداكن'}</button><button className="mobile-menu" onClick={() => setIsDropdownOpen((v) => !v)} aria-label="فتح القائمة">☰</button></div></div>
      <nav className={`main-nav ${isDropdownOpen ? 'nav-open' : ''}`} aria-label="التنقل الرئيسي"><button className={route === '/' ? 'active' : ''} onClick={() => go('/')}>الرئيسية</button><button className={route === '/recitations' ? 'active' : ''} onClick={() => go('/recitations')}>التلاوات</button><button className={route === '/quran' ? 'active' : ''} onClick={() => go('/quran')}>القرآن الكريم</button><button className={route === '/hadith' ? 'active' : ''} onClick={() => go('/hadith')}>الأحاديث النبوية ﷺ</button><button className={route === '/prophets' ? 'active' : ''} onClick={() => go('/prophets')}>قصص الأنبياء</button><button className={route === '/adhkar' ? 'active' : ''} onClick={() => go('/adhkar')}>الأذكار والأدعية</button><button className={route === '/sunnah' ? 'active' : ''} onClick={() => go('/sunnah')}>سنن النبي ﷺ</button></nav></header>
    <main className="main-content">{route === '/' && <Home go={go} />}{route === '/recitations' && <Recitations current={currentRecitation} selected={selectedSheikh} setSelected={setSelectedSheikh} open={isDropdownOpen} setOpen={setIsDropdownOpen} audioRef={audioRef} onTime={saveAudio} />}{route === '/sunnah' && <SunnahPage />}{['/quran', '/hadith', '/prophets', '/adhkar', '/seerah', '/search', '/sources'].includes(route) && <ComingSoon route={route} go={go} />}</main>
    <footer className="footer"><div><strong>منصة تلاوات الحرمين</strong><p>تلاوات ومحتوى إسلامي موثق، بتجربة هادئة ومريحة للقراءة والاستماع.</p></div><div className="footer-links"><button onClick={() => go('/quran')}>القرآن الكريم</button><button onClick={() => go('/hadith')}>الأحاديث</button><button onClick={() => go('/sources')}>المصادر والتخريج</button><button onClick={() => go('/search')}>البحث الشامل</button></div><div className="footer-bottom"><span>المحتوى يضاف تدريجيًا مع إظهار مصدره ودرجة توثيقه.</span><span>© 2026 منصة تلاوات الحرمين</span></div></footer>
  </div>
}
function Home({ go }) { return <section className="home-page"><div className="hero-card"><span className="eyebrow">من الحرمين الشريفين</span><h1>صوتٌ يفتح <em>أبواب السكينة</em></h1><p>صحبة قرآنية دائمة، وتلاوات خاشعة، ومحتوى إسلامي نحرص أن يكون مصدره واضحًا.</p><div className="hero-actions"><button className="primary-btn" onClick={() => go('/recitations')}>استمع إلى التلاوات</button><button className="secondary-btn" onClick={() => go('/quran')}>افتح القرآن الكريم</button></div></div><div className="feature-grid"><Feature icon="📖" title="القرآن الكريم" text="واجهة قراءة هادئة" go={go} path="/quran" /><Feature icon="🕋" title="الأحاديث النبوية ﷺ" text="مع المصدر والتخريج" go={go} path="/hadith" /><Feature icon="🤲" title="الأذكار والأدعية" text="محتوى منظم وموثق" go={go} path="/adhkar" /></div></section> }
function Feature({ icon, title, text, go, path }) { return <button className="feature-card" onClick={() => go(path)}><span>{icon}</span><strong>{title}</strong><small>{text}</small></button> }
function Recitations({ current, selected, setSelected, open, setOpen, audioRef, onTime }) { return <section className="recitations-page"><div className="section-heading"><span className="eyebrow">المكتبة الصوتية</span><h1>تلاوات <em>خاشعة</em></h1><p>اختر اسم الشيخ، ثم استمع إلى التلاوة من المسجد الحرام.</p></div><div className="select-wrap"><button className="sheikh-select" onClick={() => setOpen(!open)} aria-expanded={open}><span>{selected}</span><span>{open ? '▲' : '▼'}</span></button>{open && <div className="sheikh-options">{sheikhsData.map((s) => <button key={s.name} className={selected === s.name ? 'selected' : ''} onClick={() => { setSelected(s.name); setOpen(false) }}>{s.name}</button>)}</div>}</div><article className="recitation-card"><div className="recitation-meta"><div><h2>{current.title}</h2><p>{current.surah}</p></div><span className="location-badge">{current.location}</span></div><audio ref={audioRef} key={current.audioSrc} controls onTimeUpdate={onTime} onPause={onTime} onEnded={() => localStorage.setItem(STORAGE.audio, '0')}><source src={current.audioSrc} type="audio/mpeg" />متصفحك لا يدعم مشغل الصوت.</audio><small className="save-note">يتم حفظ آخر موضع استماع تلقائيًا على هذا الجهاز.</small></article></section> }
function ComingSoon({ route, go }) { return <section className="placeholder-page"><span className="placeholder-icon">✦</span><h1>{routeLabels[route]}</h1><p>هذا القسم مهيأ ضمن هيكل المنصة، وسيتم تزويده تدريجيًا بالمحتوى الموثق ومصادره.</p><button className="primary-btn" onClick={() => go('/recitations')}>العودة إلى التلاوات</button></section> }
